---
name: Deploy Chrome Extension
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: Create ZIP file
        run: zip -r extension.zip * -x "*.git*"

      - name: Publish to Chrome Web Store
        uses: fregante/chrome-webstore-upload@v3
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          extension-id: ${{ secrets.CHROME_WEBSTORE_EXTENSION_ID }}
          source: './extension.zip'
