---
name: Deploy Chrome Extension
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth-oauthlib google-auth-httplib2 \
          google-api-python-client

      - name: Create ZIP file
        run: zip -r extension.zip * -x "*.git*"

      - name: Decode OAuth
        run: |
          echo ${{ secrets.OAUTH_CLIENT_UPLOAD }} | \
          base64 --decode > oauth_client_file.json

      - name: Deploy to Chrome Web Store
        env:
          EXTENSION_ID: ${{ secrets.CHROME_WEBSTORE_EXTENSION_ID }}
          VERSION_ID: ${{ github.event.input.version }}
        run: python .github/workflows/deploy_script.py
